language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
env:
  - 'RAILS_VERSION="5.1" AMS_VERSION="0.10.7"'
  - 'RAILS_VERSION="5.2" AMS_VERSION="0.10.12"'
  - 'RAILS_VERSION="6.1" AMS_VERSION="0.10.13"'
